---
- name: Playbook to configure ansible controller organizations post installation
  hosts: localhost
  connection: local

  vars:
    controller_validate_certs: false

  vars_files: 
    - controller_configs/controller_auth.yml
    - vars/controller_organizations.json
  
  
  roles:
    - redhat_cop.controller_configuration.organizations
       
       