---
- name: Playbook to configure ansible controller user accounts post installation
  hosts: localhost
  connection: local

  vars:
    controller_validate_certs: false
  vars_files: 
    - controller_configs/controller_auth.yml
    - vars/controller_credentials.yml
  
  
  roles:
    - redhat_cop.controller_configuration.credentials

       
       