---
- name: Playbook to configure ansible controller job templates post installation
  hosts: localhost
  connection: local

  vars:
    controller_validate_certs: false
  vars_files: 
    - controller_configs/controller_auth.yaml
    - vars/controller_job_templates.json

  
  
  roles:
    - redhat_cop.controller_configuration.job_templates

  
       