---
- name: Playbook to configure ansible controller user accounts post installation
  hosts: localhost
  connection: local

  vars:
    controller_validate_certs: false

  vars_files: 
    - controller_configs/controller_settings.yml
    - vars/controller_workflow_job_templates.json
  
  roles:
    - redhat_cop.controller_configuration.workflow_job_templates