---
- name: extract {{ item }} asset
  ansible.builtin.command: >
            /usr/bin/jq '.assets.{{ item }}' files/assets.json
  register: jq_results

- debug:
    var: jq_results

- name: Set jq {{ item }} assets var 
  ansible.builtin.set_fact:
    controller_var: "{{ jq_results.stdout|from_json | to_nice_yaml( width=50, explicit_start=True, explicit_end=True)}}"

- name: Create {{ item }} var file
  ansible.builtin.template:
    src: templates/controller_{{ item }}.yml.j2
    dest: vars/controller_{{ item }}.yml
    force: yes
         
