---
- name: Playbook to export configs from ansible controller
  hosts: localhost
  connection: local
  gather_facts: true

  vars:

    controller_assets_keys:
      - organizations
      - job_templates
      - projects
      - workflow_job_templates
      - credentials

  collections:
    - ansible.controller

  tasks:

    - name: Export all assets
      ansible.controller.export:
       all: True
      register: result

    - name: Copy results to assets file
      ansible.builtin.copy:
        content: "{{ result }}"
        dest: files/assets.json
        force: yes
        
    - name: Create assets variables
      ansible.builtin.include_tasks: controller_export.yml
      loop: "{{ controller_assets_keys }}"
