---

- name: Export all assets
  ansible.controller.export:
    all: True
  register: result

- name: Copy results to assets file
  ansible.builtin.copy:
    content: "{{ result }}"
    dest: files/assets.json
    force: yes

- name: extract  asset
  ansible.builtin.command: >
            /usr/bin/jq '.assets.{{ item }}' 
            files/assets.json
  register: jq_results

- name: Set jq assets var 
  set_fact:
    controller_: "jq_{{ item }}_results.stdout| from_json | to_nice_json "
            

- name: Create {{ item }} var file
  ansible.builtin.template:
    src: templates/controller_{{ item }}.json.j2
    dest: vars/controller_{{ item }}.json
    force: yes
         
