---
- name: extract {{ item }} asset
  ansible.builtin.command: >
            /usr/bin/jq '.assets.{{ item }}' files/assets.json
  register: jq_results

- debug:
    var: jq_results

- name: Set jq {{ item }} assets var 
  set_fact:
    controller_{{ item }}_var: "jq_results.stdout| from_json | to_nice_json "
            

- name: Create {{ item }} var file
  ansible.builtin.template:
    src: templates/controller_{{ item }}.json.j2
    dest: vars/controller_{{ item }}.json
    force: yes
         
